# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyname',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bench.CurrencyName'),
        ),
    ]
